# Generated by Django 5.2.17 on 2026-10-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('deposit', models.PositiveBigIntegerField()),
                ('monthly_rent', models.PositiveBigIntegerField()),
                ('alternative_deposit', models.PositiveBigIntegerField(blank=True, null=True)),
                ('alternative_rent', models.PositiveBigIntegerField(blank=True, null=True)),
                ('area_m2', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('construction_year', models.PositiveSmallIntegerField()),
                ('renovated', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('distance_to_work_km', models.FloatField()),
                ('distances', models.JSONField(default=dict)),
                ('natural_light', models.FloatField(default=0.5)),
                ('quietness', models.FloatField(default=0.5)),
                ('layout_quality', models.FloatField(default=0.5)),
                ('access_quality', models.FloatField(default=0.5)),
                ('evidence', models.JSONField(default=list)),
                ('data_conflicts', models.JSONField(default=list)),
                ('image_name', models.CharField(max_length=40)),
            ],
        ),
    ]
