# Generated by Django 5.2.17 on 2026-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='tehran', max_length=60),
        ),
        migrations.AddField(
            model_name='listing',
            name='data_source',
            field=models.CharField(db_index=True, default='synthetic', max_length=12),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_radius_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='renovation_claim',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='listing',
            name='access_quality',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='balcony',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='construction_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='distance_to_work_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='elevator',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='layout_quality',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='natural_light',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quietness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='renovated',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='storage',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
